import os
from jinja2 import Template

class ReportGenerator:
    def __init__(self, output_dir="outputs"):
        self.output_dir = output_dir

    def generate_html(self, stats, summary_text):
        template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>GitHub Yearbook</title>
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; max-width: 1000px; margin: 0 auto; padding: 40px; background: #f9f9f9; }
                h1 { text-align: center; color: #2c3e50; margin-bottom: 10px; }
                .subtitle { text-align: center; color: #7f8c8d; margin-bottom: 40px; }
                .summary-card { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); margin-bottom: 40px; }
                .summary-text { font-size: 1.2em; line-height: 1.6; font-style: italic; color: #555; border-left: 4px solid #3498db; padding-left: 20px; }
                .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }
                .stat-item { background: white; padding: 20px; border-radius: 8px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }
                .stat-value { font-size: 2.5em; font-weight: bold; color: #3498db; }
                .stat-label { color: #95a5a6; text-transform: uppercase; font-size: 0.9em; letter-spacing: 1px; }
                .chart-section { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); margin-bottom: 30px; }
                .chart-section img { width: 100%; height: auto; border-radius: 5px; }
                .chart-title { font-size: 1.2em; font-weight: bold; margin-bottom: 15px; color: #2c3e50; }
                .footer { text-align: center; margin-top: 50px; color: #bdc3c7; font-size: 0.8em; }
            </style>
        </head>
        <body>
            <h1>GitHub Yearbook</h1>
            <div class="subtitle">2024/08/01 – 2025/11/04</div>

            <div class="summary-card">
                <div class="summary-text">
                    {{ summary_text }}
                </div>
            </div>

            <div class="stats-grid">
                <div class="stat-item">
                    <div class="stat-value">{{ stats.total_commits }}</div>
                    <div class="stat-label">Total Commits</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">{{ stats.total_repos }}</div>
                    <div class="stat-label">Active Repos</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">{{ stats.peak_month }}</div>
                    <div class="stat-label">Peak Month</div>
                </div>
            </div>

            <div class="chart-section">
                <div class="chart-title">Activity Timeline</div>
                <img src="timeline.png" alt="Timeline">
            </div>

            <div class="chart-section">
                <div class="chart-title">Project Contributions</div>
                <img src="projects.png" alt="Projects">
            </div>

            <div class="chart-section" style="display: flex; gap: 20px;">
                <div style="flex: 1;">
                    <div class="chart-title">Languages</div>
                    <img src="languages.png" alt="Languages">
                </div>
                <div style="flex: 1;">
                    <div class="chart-title">Topics</div>
                    <img src="wordcloud.png" alt="Wordcloud">
                </div>
            </div>

            <div class="footer">
                Generated by GitHub Yearbook Tool
            </div>
        </body>
        </html>
        """
        
        template = Template(template_str)
        html_content = template.render(stats=stats, summary_text=summary_text)
        
        with open(os.path.join(self.output_dir, 'yearbook.html'), 'w') as f:
            f.write(html_content)
        
        return os.path.join(self.output_dir, 'yearbook.html')
