import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import os

class Visualizer:
    def __init__(self, output_dir="outputs"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        # Set style
        plt.style.use('ggplot')
        sns.set_theme(style="whitegrid")

    def plot_timeline(self, monthly_stats):
        if monthly_stats.empty:
            return
        
        plt.figure(figsize=(12, 6))
        sns.lineplot(data=monthly_stats, x='date', y='count', marker='o', linewidth=2.5, color='#4a90e2')
        plt.title('Monthly Commit Activity', fontsize=16, fontweight='bold')
        plt.xlabel('Date')
        plt.ylabel('Commits')
        plt.tight_layout()
        plt.savefig(os.path.join(self.output_dir, 'timeline.png'), dpi=300)
        plt.close()

    def plot_languages(self, lang_stats):
        if not lang_stats:
            return
        
        # Filter small slices
        total = sum(lang_stats.values())
        data = {k: v for k, v in lang_stats.items() if v/total > 0.01}
        
        plt.figure(figsize=(10, 10))
        plt.pie(data.values(), labels=data.keys(), autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
        plt.title('Language Distribution', fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(self.output_dir, 'languages.png'), dpi=300)
        plt.close()

    def plot_wordcloud(self, keywords):
        if not keywords:
            return
        
        # Convert list of tuples to dict
        word_freq = dict(keywords)
        
        wc = WordCloud(width=800, height=400, background_color='white', colormap='viridis').generate_from_frequencies(word_freq)
        
        plt.figure(figsize=(12, 6))
        plt.imshow(wc, interpolation='bilinear')
        plt.axis('off')
        plt.title('Commit Message Topics', fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(self.output_dir, 'wordcloud.png'), dpi=300)
        plt.close()

    def plot_projects(self, project_stats):
        if project_stats.empty:
            return
        
        top_projects = project_stats.head(10)
        
        plt.figure(figsize=(12, 6))
        sns.barplot(data=top_projects, x='count', y='repo', palette='viridis')
        plt.title('Top Projects by Commits', fontsize=16, fontweight='bold')
        plt.xlabel('Commits')
        plt.ylabel('Repository')
        plt.tight_layout()
        plt.savefig(os.path.join(self.output_dir, 'projects.png'), dpi=300)
        plt.close()

    def generate_social_card(self, stats):
        # Create a dark themed card
        plt.figure(figsize=(8, 10), facecolor='#1a1a1a')
        ax = plt.gca()
        ax.set_facecolor('#1a1a1a')
        ax.axis('off')
        
        # Title
        plt.text(0.5, 0.9, "GitHub Yearbook", ha='center', va='center', color='white', fontsize=24, fontweight='bold', transform=ax.transAxes)
        plt.text(0.5, 0.85, "2024-2025", ha='center', va='center', color='#888', fontsize=14, transform=ax.transAxes)
        
        # Stats
        plt.text(0.5, 0.7, f"{stats['total_commits']}", ha='center', va='center', color='#4a90e2', fontsize=48, fontweight='bold', transform=ax.transAxes)
        plt.text(0.5, 0.65, "Total Commits", ha='center', va='center', color='#aaa', fontsize=12, transform=ax.transAxes)
        
        plt.text(0.3, 0.5, f"{stats['total_repos']}", ha='center', va='center', color='#e74c3c', fontsize=32, fontweight='bold', transform=ax.transAxes)
        plt.text(0.3, 0.45, "Active Repos", ha='center', va='center', color='#aaa', fontsize=10, transform=ax.transAxes)
        
        plt.text(0.7, 0.5, f"{stats['peak_month'].split(' ')[0]}", ha='center', va='center', color='#2ecc71', fontsize=28, fontweight='bold', transform=ax.transAxes)
        plt.text(0.7, 0.45, "Peak Month", ha='center', va='center', color='#aaa', fontsize=10, transform=ax.transAxes)
        
        # Top Project
        plt.text(0.5, 0.3, f"Top Project: {stats['top_repo']}", ha='center', va='center', color='white', fontsize=16, fontweight='bold', transform=ax.transAxes)
        
        # Footer
        plt.text(0.5, 0.1, "Generated by GitHub Yearbook", ha='center', va='center', color='#555', fontsize=8, transform=ax.transAxes)
        
        plt.tight_layout()
        plt.savefig(os.path.join(self.output_dir, 'social_card.png'), dpi=300, bbox_inches='tight')
        plt.close()
